spring:
  datasource:
    name: vanilla
    url: jdbc:postgresql://localhost:5432/vanilla
    username: sky
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

app:
  cors:
    origins:
     http://localhost:5173