spring:
  datasource:
    name: vanilla
    url: jdbc:postgresql://localhost:5432/vanilla
    username: sky
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    property:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

