spring:
  datasource:
    name: vanilla
    url: jdbc:postgresql://localhost:5432/vanilla
    username: sky
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

app:
  cors:
    origins:
     http://localhost:5173

springdoc:
  api-docs:
    enabled: false #disable at deployment, available at dev and write the result to static json file
  swagger-ui:
    enabled: false

